# Generated by Django 4.2.5 on 2023-09-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SIPCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_period', models.PositiveIntegerField()),
            ],
        ),
    ]
